### ISSUE TITLE
Support all binaries

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/clog-cli#2]
Currently support is only available for Mac. Would like to support all binaries. The only problem is I don't know how to configure my `package.json` so that [the bin property](https://github.com/kentcdodds/clog-cli/blob/master/package.json#L13) indicates which binary to install based on the platform...

**Comment by othiym23** [comment]
If you're not using `node-gyp` to build the binary, you should create separate tarballs for each binary and then write a downloader script like `phantomjs`'s that uses `process.platform` to decide which one to download. That way you don't use up a bunch of disk space unnecessarily and only have to switch based on platform once, at install time.

If you wat to bundle all of the different binaries into one package, just name them something like `clog-darwin` and then write a `postinstall` script that symlinks based on `process.platform`. The only thing that's weird about that is that sone versions of windows will require you to be an Administratir to create the link. If that turns out to affect your users, then a wrapper script using `child_process` will probably be necessary.

However you do it, `process.platform` will probably be in there somewhere.

**Comment by kentcdodds** [comment]
Awesome. Thanks for that. It sounds like the right/best solution would be to do what `phantomjs` is doing as you suggested. I'll give that a look. Thanks!
